import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Tabs from './tabs/index';
import Footer from './footer/index';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='flex h-screen bg-themeBg p-0'>
				<div className='flex flex-col w-full min-h-screen'>
					<Tabs />
					<div className='mt-32'>{children}</div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
